# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_server import message_transmission_pb2 as message__transmission__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in message_transmission_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessageTransmissionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.task_processor = channel.unary_unary(
                '/MessageTransmission/task_processor',
                request_serializer=message__transmission__pb2.MessageRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.MessageReply.FromString,
                _registered_method=True)
        self.get_queue_info = channel.unary_unary(
                '/MessageTransmission/get_queue_info',
                request_serializer=message__transmission__pb2.InfoRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.InfoReply.FromString,
                _registered_method=True)
        self.frame_processor = channel.stream_unary(
                '/MessageTransmission/frame_processor',
                request_serializer=message__transmission__pb2.FrameRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.FrameReply.FromString,
                _registered_method=True)
        self.train_model_request = channel.unary_unary(
                '/MessageTransmission/train_model_request',
                request_serializer=message__transmission__pb2.TrainRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.TrainReply.FromString,
                _registered_method=True)
        self.split_train_request = channel.unary_unary(
                '/MessageTransmission/split_train_request',
                request_serializer=message__transmission__pb2.SplitTrainRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.SplitTrainReply.FromString,
                _registered_method=True)
        self.query_resource = channel.unary_unary(
                '/MessageTransmission/query_resource',
                request_serializer=message__transmission__pb2.ResourceRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.ResourceReply.FromString,
                _registered_method=True)
        self.bandwidth_probe = channel.unary_unary(
                '/MessageTransmission/bandwidth_probe',
                request_serializer=message__transmission__pb2.BandwidthProbeRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.BandwidthProbeReply.FromString,
                _registered_method=True)


class MessageTransmissionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def task_processor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_queue_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def frame_processor(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def train_model_request(self, request, context):
        """Cloud-side continual learning: edge sends collected frame indices,
        cloud retrains the lightweight model and returns updated weights.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def split_train_request(self, request, context):
        """Split-learning continual learning: edge sends intermediate features
        (cached on shared filesystem), cloud annotates drift frames only,
        then trains server-side model (rpn + roi_heads) on all features.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def query_resource(self, request, context):
        """Resource-aware CL trigger: edge queries cloud resource utilisation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bandwidth_probe(self, request, context):
        """Bandwidth estimation: edge sends a small payload, cloud echoes it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageTransmissionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'task_processor': grpc.unary_unary_rpc_method_handler(
                    servicer.task_processor,
                    request_deserializer=message__transmission__pb2.MessageRequest.FromString,
                    response_serializer=message__transmission__pb2.MessageReply.SerializeToString,
            ),
            'get_queue_info': grpc.unary_unary_rpc_method_handler(
                    servicer.get_queue_info,
                    request_deserializer=message__transmission__pb2.InfoRequest.FromString,
                    response_serializer=message__transmission__pb2.InfoReply.SerializeToString,
            ),
            'frame_processor': grpc.stream_unary_rpc_method_handler(
                    servicer.frame_processor,
                    request_deserializer=message__transmission__pb2.FrameRequest.FromString,
                    response_serializer=message__transmission__pb2.FrameReply.SerializeToString,
            ),
            'train_model_request': grpc.unary_unary_rpc_method_handler(
                    servicer.train_model_request,
                    request_deserializer=message__transmission__pb2.TrainRequest.FromString,
                    response_serializer=message__transmission__pb2.TrainReply.SerializeToString,
            ),
            'split_train_request': grpc.unary_unary_rpc_method_handler(
                    servicer.split_train_request,
                    request_deserializer=message__transmission__pb2.SplitTrainRequest.FromString,
                    response_serializer=message__transmission__pb2.SplitTrainReply.SerializeToString,
            ),
            'query_resource': grpc.unary_unary_rpc_method_handler(
                    servicer.query_resource,
                    request_deserializer=message__transmission__pb2.ResourceRequest.FromString,
                    response_serializer=message__transmission__pb2.ResourceReply.SerializeToString,
            ),
            'bandwidth_probe': grpc.unary_unary_rpc_method_handler(
                    servicer.bandwidth_probe,
                    request_deserializer=message__transmission__pb2.BandwidthProbeRequest.FromString,
                    response_serializer=message__transmission__pb2.BandwidthProbeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MessageTransmission', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MessageTransmission', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageTransmission(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def task_processor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/task_processor',
            message__transmission__pb2.MessageRequest.SerializeToString,
            message__transmission__pb2.MessageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_queue_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/get_queue_info',
            message__transmission__pb2.InfoRequest.SerializeToString,
            message__transmission__pb2.InfoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def frame_processor(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/MessageTransmission/frame_processor',
            message__transmission__pb2.FrameRequest.SerializeToString,
            message__transmission__pb2.FrameReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def train_model_request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/train_model_request',
            message__transmission__pb2.TrainRequest.SerializeToString,
            message__transmission__pb2.TrainReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def split_train_request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/split_train_request',
            message__transmission__pb2.SplitTrainRequest.SerializeToString,
            message__transmission__pb2.SplitTrainReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def query_resource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/query_resource',
            message__transmission__pb2.ResourceRequest.SerializeToString,
            message__transmission__pb2.ResourceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def bandwidth_probe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/bandwidth_probe',
            message__transmission__pb2.BandwidthProbeRequest.SerializeToString,
            message__transmission__pb2.BandwidthProbeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
