# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_server.protos import message_transmission_pb2 as message__transmission__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in message_transmission_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessageTransmissionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.train_model_request = channel.unary_unary(
                '/MessageTransmission/train_model_request',
                request_serializer=message__transmission__pb2.TrainRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.TrainReply.FromString,
                _registered_method=True)
        self.continual_learning_request = channel.unary_unary(
                '/MessageTransmission/continual_learning_request',
                request_serializer=message__transmission__pb2.ContinualLearningRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.ContinualLearningReply.FromString,
                _registered_method=True)
        self.sync_samples = channel.unary_unary(
                '/MessageTransmission/sync_samples',
                request_serializer=message__transmission__pb2.SampleSyncRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.SampleSyncReply.FromString,
                _registered_method=True)
        self.submit_training_job = channel.unary_unary(
                '/MessageTransmission/submit_training_job',
                request_serializer=message__transmission__pb2.SubmitTrainingJobRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.SubmitTrainingJobReply.FromString,
                _registered_method=True)
        self.get_training_job_status = channel.unary_unary(
                '/MessageTransmission/get_training_job_status',
                request_serializer=message__transmission__pb2.TrainingJobStatusRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.TrainingJobStatusReply.FromString,
                _registered_method=True)
        self.download_trained_model = channel.unary_unary(
                '/MessageTransmission/download_trained_model',
                request_serializer=message__transmission__pb2.DownloadTrainedModelRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.DownloadTrainedModelReply.FromString,
                _registered_method=True)
        self.report_edge_model_version = channel.unary_unary(
                '/MessageTransmission/report_edge_model_version',
                request_serializer=message__transmission__pb2.ReportEdgeModelVersionRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.ReportEdgeModelVersionReply.FromString,
                _registered_method=True)
        self.cancel_training_job = channel.unary_unary(
                '/MessageTransmission/cancel_training_job',
                request_serializer=message__transmission__pb2.CancelTrainingJobRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.CancelTrainingJobReply.FromString,
                _registered_method=True)
        self.query_resource = channel.unary_unary(
                '/MessageTransmission/query_resource',
                request_serializer=message__transmission__pb2.ResourceRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.ResourceReply.FromString,
                _registered_method=True)
        self.bandwidth_probe = channel.unary_unary(
                '/MessageTransmission/bandwidth_probe',
                request_serializer=message__transmission__pb2.BandwidthProbeRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.BandwidthProbeReply.FromString,
                _registered_method=True)
        self.RegisterEdge = channel.unary_unary(
                '/MessageTransmission/RegisterEdge',
                request_serializer=message__transmission__pb2.BaselineRegisterEdgeRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.BaselineAck.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/MessageTransmission/Heartbeat',
                request_serializer=message__transmission__pb2.BaselineHeartbeatRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.BaselineAck.FromString,
                _registered_method=True)
        self.UploadFrame = channel.unary_unary(
                '/MessageTransmission/UploadFrame',
                request_serializer=message__transmission__pb2.BaselineFrameRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.BaselineAck.FromString,
                _registered_method=True)
        self.UploadKeyFrame = channel.unary_unary(
                '/MessageTransmission/UploadKeyFrame',
                request_serializer=message__transmission__pb2.BaselineFrameRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.BaselineAck.FromString,
                _registered_method=True)
        self.UploadPrediction = channel.unary_unary(
                '/MessageTransmission/UploadPrediction',
                request_serializer=message__transmission__pb2.BaselineFrameRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.BaselineAck.FromString,
                _registered_method=True)
        self.RequestCloudInference = channel.unary_unary(
                '/MessageTransmission/RequestCloudInference',
                request_serializer=message__transmission__pb2.BaselineInferenceRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.BaselineInferenceReply.FromString,
                _registered_method=True)
        self.PollCommand = channel.unary_unary(
                '/MessageTransmission/PollCommand',
                request_serializer=message__transmission__pb2.BaselineCommandRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.BaselineCommandReply.FromString,
                _registered_method=True)
        self.DownloadInferenceResult = channel.unary_unary(
                '/MessageTransmission/DownloadInferenceResult',
                request_serializer=message__transmission__pb2.BaselineInferenceRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.BaselineInferenceReply.FromString,
                _registered_method=True)
        self.RequestTraining = channel.unary_unary(
                '/MessageTransmission/RequestTraining',
                request_serializer=message__transmission__pb2.BaselineTrainingRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.BaselineTrainingReply.FromString,
                _registered_method=True)
        self.PollTrainingJob = channel.unary_unary(
                '/MessageTransmission/PollTrainingJob',
                request_serializer=message__transmission__pb2.BaselineTrainingStatusRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.BaselineTrainingStatusReply.FromString,
                _registered_method=True)
        self.DownloadModelUpdate = channel.unary_unary(
                '/MessageTransmission/DownloadModelUpdate',
                request_serializer=message__transmission__pb2.BaselineModelUpdateRequest.SerializeToString,
                response_deserializer=message__transmission__pb2.BaselineModelUpdateReply.FromString,
                _registered_method=True)


class MessageTransmissionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def train_model_request(self, request, context):
        """Cloud-side continual learning: edge sends collected frame indices,
        cloud retrains the lightweight model and returns updated weights.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def continual_learning_request(self, request, context):
        """Versioned continual-learning bundle upload for the fixed-split pipeline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sync_samples(self, request, context):
        """Sharded sample pool exchange without creating a training job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_training_job(self, request, context):
        """Async training job submission for edge-triggered continual learning.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_training_job_status(self, request, context):
        """Poll async training job status by job_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def download_trained_model(self, request, context):
        """Download trained model for a completed async training job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def report_edge_model_version(self, request, context):
        """Report that an edge has applied a model update.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cancel_training_job(self, request, context):
        """Cancel a queued or running training job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def query_resource(self, request, context):
        """Resource-aware CL trigger: edge queries cloud resource utilisation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bandwidth_probe(self, request, context):
        """Bandwidth estimation: edge sends a small payload, cloud echoes it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterEdge(self, request, context):
        """Distributed baseline deployment RPCs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadKeyFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadPrediction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCloudInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadInferenceResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollTrainingJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadModelUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageTransmissionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'train_model_request': grpc.unary_unary_rpc_method_handler(
                    servicer.train_model_request,
                    request_deserializer=message__transmission__pb2.TrainRequest.FromString,
                    response_serializer=message__transmission__pb2.TrainReply.SerializeToString,
            ),
            'continual_learning_request': grpc.unary_unary_rpc_method_handler(
                    servicer.continual_learning_request,
                    request_deserializer=message__transmission__pb2.ContinualLearningRequest.FromString,
                    response_serializer=message__transmission__pb2.ContinualLearningReply.SerializeToString,
            ),
            'sync_samples': grpc.unary_unary_rpc_method_handler(
                    servicer.sync_samples,
                    request_deserializer=message__transmission__pb2.SampleSyncRequest.FromString,
                    response_serializer=message__transmission__pb2.SampleSyncReply.SerializeToString,
            ),
            'submit_training_job': grpc.unary_unary_rpc_method_handler(
                    servicer.submit_training_job,
                    request_deserializer=message__transmission__pb2.SubmitTrainingJobRequest.FromString,
                    response_serializer=message__transmission__pb2.SubmitTrainingJobReply.SerializeToString,
            ),
            'get_training_job_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_training_job_status,
                    request_deserializer=message__transmission__pb2.TrainingJobStatusRequest.FromString,
                    response_serializer=message__transmission__pb2.TrainingJobStatusReply.SerializeToString,
            ),
            'download_trained_model': grpc.unary_unary_rpc_method_handler(
                    servicer.download_trained_model,
                    request_deserializer=message__transmission__pb2.DownloadTrainedModelRequest.FromString,
                    response_serializer=message__transmission__pb2.DownloadTrainedModelReply.SerializeToString,
            ),
            'report_edge_model_version': grpc.unary_unary_rpc_method_handler(
                    servicer.report_edge_model_version,
                    request_deserializer=message__transmission__pb2.ReportEdgeModelVersionRequest.FromString,
                    response_serializer=message__transmission__pb2.ReportEdgeModelVersionReply.SerializeToString,
            ),
            'cancel_training_job': grpc.unary_unary_rpc_method_handler(
                    servicer.cancel_training_job,
                    request_deserializer=message__transmission__pb2.CancelTrainingJobRequest.FromString,
                    response_serializer=message__transmission__pb2.CancelTrainingJobReply.SerializeToString,
            ),
            'query_resource': grpc.unary_unary_rpc_method_handler(
                    servicer.query_resource,
                    request_deserializer=message__transmission__pb2.ResourceRequest.FromString,
                    response_serializer=message__transmission__pb2.ResourceReply.SerializeToString,
            ),
            'bandwidth_probe': grpc.unary_unary_rpc_method_handler(
                    servicer.bandwidth_probe,
                    request_deserializer=message__transmission__pb2.BandwidthProbeRequest.FromString,
                    response_serializer=message__transmission__pb2.BandwidthProbeReply.SerializeToString,
            ),
            'RegisterEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEdge,
                    request_deserializer=message__transmission__pb2.BaselineRegisterEdgeRequest.FromString,
                    response_serializer=message__transmission__pb2.BaselineAck.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=message__transmission__pb2.BaselineHeartbeatRequest.FromString,
                    response_serializer=message__transmission__pb2.BaselineAck.SerializeToString,
            ),
            'UploadFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFrame,
                    request_deserializer=message__transmission__pb2.BaselineFrameRequest.FromString,
                    response_serializer=message__transmission__pb2.BaselineAck.SerializeToString,
            ),
            'UploadKeyFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadKeyFrame,
                    request_deserializer=message__transmission__pb2.BaselineFrameRequest.FromString,
                    response_serializer=message__transmission__pb2.BaselineAck.SerializeToString,
            ),
            'UploadPrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPrediction,
                    request_deserializer=message__transmission__pb2.BaselineFrameRequest.FromString,
                    response_serializer=message__transmission__pb2.BaselineAck.SerializeToString,
            ),
            'RequestCloudInference': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCloudInference,
                    request_deserializer=message__transmission__pb2.BaselineInferenceRequest.FromString,
                    response_serializer=message__transmission__pb2.BaselineInferenceReply.SerializeToString,
            ),
            'PollCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.PollCommand,
                    request_deserializer=message__transmission__pb2.BaselineCommandRequest.FromString,
                    response_serializer=message__transmission__pb2.BaselineCommandReply.SerializeToString,
            ),
            'DownloadInferenceResult': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadInferenceResult,
                    request_deserializer=message__transmission__pb2.BaselineInferenceRequest.FromString,
                    response_serializer=message__transmission__pb2.BaselineInferenceReply.SerializeToString,
            ),
            'RequestTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTraining,
                    request_deserializer=message__transmission__pb2.BaselineTrainingRequest.FromString,
                    response_serializer=message__transmission__pb2.BaselineTrainingReply.SerializeToString,
            ),
            'PollTrainingJob': grpc.unary_unary_rpc_method_handler(
                    servicer.PollTrainingJob,
                    request_deserializer=message__transmission__pb2.BaselineTrainingStatusRequest.FromString,
                    response_serializer=message__transmission__pb2.BaselineTrainingStatusReply.SerializeToString,
            ),
            'DownloadModelUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadModelUpdate,
                    request_deserializer=message__transmission__pb2.BaselineModelUpdateRequest.FromString,
                    response_serializer=message__transmission__pb2.BaselineModelUpdateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MessageTransmission', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MessageTransmission', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageTransmission(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def train_model_request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/train_model_request',
            message__transmission__pb2.TrainRequest.SerializeToString,
            message__transmission__pb2.TrainReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def continual_learning_request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/continual_learning_request',
            message__transmission__pb2.ContinualLearningRequest.SerializeToString,
            message__transmission__pb2.ContinualLearningReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sync_samples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/sync_samples',
            message__transmission__pb2.SampleSyncRequest.SerializeToString,
            message__transmission__pb2.SampleSyncReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def submit_training_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/submit_training_job',
            message__transmission__pb2.SubmitTrainingJobRequest.SerializeToString,
            message__transmission__pb2.SubmitTrainingJobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_training_job_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/get_training_job_status',
            message__transmission__pb2.TrainingJobStatusRequest.SerializeToString,
            message__transmission__pb2.TrainingJobStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def download_trained_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/download_trained_model',
            message__transmission__pb2.DownloadTrainedModelRequest.SerializeToString,
            message__transmission__pb2.DownloadTrainedModelReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def report_edge_model_version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/report_edge_model_version',
            message__transmission__pb2.ReportEdgeModelVersionRequest.SerializeToString,
            message__transmission__pb2.ReportEdgeModelVersionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cancel_training_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/cancel_training_job',
            message__transmission__pb2.CancelTrainingJobRequest.SerializeToString,
            message__transmission__pb2.CancelTrainingJobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def query_resource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/query_resource',
            message__transmission__pb2.ResourceRequest.SerializeToString,
            message__transmission__pb2.ResourceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def bandwidth_probe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/bandwidth_probe',
            message__transmission__pb2.BandwidthProbeRequest.SerializeToString,
            message__transmission__pb2.BandwidthProbeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/RegisterEdge',
            message__transmission__pb2.BaselineRegisterEdgeRequest.SerializeToString,
            message__transmission__pb2.BaselineAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/Heartbeat',
            message__transmission__pb2.BaselineHeartbeatRequest.SerializeToString,
            message__transmission__pb2.BaselineAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/UploadFrame',
            message__transmission__pb2.BaselineFrameRequest.SerializeToString,
            message__transmission__pb2.BaselineAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadKeyFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/UploadKeyFrame',
            message__transmission__pb2.BaselineFrameRequest.SerializeToString,
            message__transmission__pb2.BaselineAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/UploadPrediction',
            message__transmission__pb2.BaselineFrameRequest.SerializeToString,
            message__transmission__pb2.BaselineAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestCloudInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/RequestCloudInference',
            message__transmission__pb2.BaselineInferenceRequest.SerializeToString,
            message__transmission__pb2.BaselineInferenceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/PollCommand',
            message__transmission__pb2.BaselineCommandRequest.SerializeToString,
            message__transmission__pb2.BaselineCommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadInferenceResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/DownloadInferenceResult',
            message__transmission__pb2.BaselineInferenceRequest.SerializeToString,
            message__transmission__pb2.BaselineInferenceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/RequestTraining',
            message__transmission__pb2.BaselineTrainingRequest.SerializeToString,
            message__transmission__pb2.BaselineTrainingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollTrainingJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/PollTrainingJob',
            message__transmission__pb2.BaselineTrainingStatusRequest.SerializeToString,
            message__transmission__pb2.BaselineTrainingStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadModelUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageTransmission/DownloadModelUpdate',
            message__transmission__pb2.BaselineModelUpdateRequest.SerializeToString,
            message__transmission__pb2.BaselineModelUpdateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
